// import Image from "next/image";
import LandingPage from "./ui/home/LandingPage";

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <LandingPage />
  );
}
